# Generated by Django 3.1.5 on 2021-01-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='container_id',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='ship_id',
        ),
        migrations.AddField(
            model_name='dockmanifest',
            name='offload',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
