# Generated by Django 3.1.5 on 2021-01-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0002_auto_20210124_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockmanifest',
            name='arrival',
            field=models.DateTimeField(help_text='yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='dockmanifest',
            name='departure',
            field=models.DateTimeField(blank=True, help_text='yyyy-mm-dd', null=True),
        ),
        migrations.AlterField(
            model_name='dockmanifest',
            name='offload',
            field=models.DateTimeField(blank=True, help_text='yyyy-mm-dd', null=True),
        ),
    ]
