# Generated by Django 3.1.5 on 2021-01-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0003_auto_20210124_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='image',
            field=models.ImageField(default='default', upload_to='ship'),
            preserve_default=False,
        ),
    ]
