# Generated by Django 3.1.5 on 2021-01-31 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0004_ship_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(max_length=30)),
                ('current_position', models.CharField(choices=[('dd', 'DUE TO OFFLOAD'), ('yy', 'NOT OFFLOADED'), ('oo', 'OFFLOADED')], default='yy', max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterModelOptions(
            name='dockmanifest',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RemoveField(
            model_name='dockmanifest',
            name='offload',
        ),
        migrations.AddField(
            model_name='dockmanifest',
            name='current_position',
            field=models.CharField(choices=[('dd', 'DUE TO OFFLOAD'), ('yy', 'NOT OFFLOADED'), ('oo', 'OFFLOADED')], default='yy', max_length=2),
        ),
        migrations.AddField(
            model_name='dockmanifest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
