# Generated by Django 3.1.3 on 2021-01-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatedIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_word_title', models.CharField(max_length=12)),
                ('rem_title', models.CharField(max_length=38)),
                ('note', models.TextField()),
                ('slide', models.ImageField(upload_to='slides')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bullet_one', models.CharField(max_length=300)),
                ('bullet_two', models.CharField(max_length=300)),
                ('bullet_three', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('second_description', models.TextField()),
                ('third_description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('second_image', models.ImageField(upload_to='services/')),
                ('third_image', models.ImageField(upload_to='services/')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_title', models.CharField(max_length=30)),
                ('rem_title', models.CharField(max_length=30, verbose_name='Remaining Title')),
                ('first_para', models.TextField(verbose_name='First Paragraph')),
                ('sec_para', models.TextField(verbose_name='Second Paragraph')),
                ('first_bul', models.TextField(verbose_name='First Bullet')),
                ('sec_bul', models.TextField(verbose_name='Second Bullet')),
                ('third_bul', models.TextField(verbose_name='Third Bullet')),
                ('conclusion', models.TextField()),
            ],
        ),
    ]
