# Generated by Django 3.1.5 on 2021-01-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(default='default', upload_to='user_profile'),
            preserve_default=False,
        ),
    ]
